Repository fregante/daily-version-action, pull requests merged in 2020-06, with the labels that each got.

#1 Document use of action outputs in readme
  README.md
Labels: documentation

#4 Make it work
  .gitattributes
  .github/workflows/test.yml
  action.yml
  distribution/index.js
  index.js
  package-lock.json
  package.json
Labels: bug

#7 Automatically set the user/email if not set
  .github/workflows/test.yml
  README.md
  distribution/index.js
  index.js
Labels: enhancement
